import 'kjv_contextual_korean_corrections.dart';

const bibleKoreanSupplement = <String, String>{
  ...kjvContextualKoreanCorrections,
  'alway': '항상, 언제나',
  'armourbearer': '병기를 든 자, 무기를 맡은 부하',
  'arrogancy': '오만, 교만',
  'bason': '대야, 주발',
  'basons': '대야들, 주발들',
  'bondmen': '종들, 노예들',
  'brasen': '놋으로 만든, 놋쇠의',
  'calledst': '불렀다, 부르짖었다 (고어, call의 2인칭 과거형)',
  'canst': '할 수 있다 (고어, can의 2인칭)',
  'cherubims': '그룹들, 하나님의 보좌를 수호하는 천사들',
  'cieled': '널판이나 목재로 입힌',
  'cloke': '겉옷; 덮개, 구실',
  'commandedst': '명하였다 (고어, command의 2인칭 과거형)',
  'didst': '하였다 (고어, do의 2인칭 과거형)',
  'dwellingplaces': '거처들, 사는 곳들',
  'emerods': '독종, 종기; 치질',
  'ephod': '에봇, 제사장이 입던 성스러운 의복',
  'fellowservant': '동료 종, 함께 섬기는 사람',
  'fellowservants': '동료 종들, 함께 섬기는 사람들',
  'firstfruits': '첫 열매, 처음 익은 소산',
  'firstripe': '처음 익은, 맨 먼저 여문',
  'forasmuch': '~이므로, ~인 까닭에',
  'fro': '이리저리, 앞뒤로',
  'fulness': '충만, 가득함',
  'gerahs': '게라들, 고대 히브리 무게 단위',
  'grisled': '회색 또는 얼룩무늬가 있는',
  'horsemen': '기병들, 말을 탄 군사들',
  'herdmen': '목자들, 가축을 돌보는 사람들',
  'hungred': '굶주린, 배고픈',
  'howbeit': '그러나, 그렇지만',
  'husbandmen': '농부들, 포도원을 가꾸는 사람들',
  'inasmuch': '~인 만큼, ~이므로',
  'intreat': '간청하다, 탄원하다',
  'intreated': '간구하였다, 간청하였다',
  'jubile': '희년, 해방을 선포하는 오십 번째 해',
  'longsuffering': '오래 참음, 인내',
  'lovingkindness': '인자, 자비, 변함없는 사랑',
  'lothe': '몹시 싫어하다, 혐오하다',
  'liers': '매복한 사람들, 복병',
  'musick': '음악',
  'oliveyards': '감람원들, 올리브 과수원들',
  'ought': '~해야 한다, ~하는 것이 마땅하다',
  'plaister': '회반죽; 회칠하다',
  'plumbline': '다림줄',
  'rereward': '후진, 뒤를 지키는 부대',
  'ringstraked': '줄무늬가 있는, 아롱진',
  'saith': '말한다 (고어, say의 3인칭 단수)',
  'saidst': '말하였다 (고어, say의 2인칭 과거형)',
  'scall': '악성 피부병, 옴',
  'shewbread': '진설병, 성소에 차려 놓은 떡',
  'shouldest': '~해야 한다, ~할 것이다 (고어, 2인칭)',
  'soever': '~든지, 어느 것이든',
  'spake': '말하였다 (고어, speak의 과거형)',
  'stablish': '굳게 세우다, 확립하다',
  'stedfast': '확고한, 흔들리지 않는',
  'stedfastly': '확고하게, 굳게',
  'stumblingblock': '걸림돌, 남을 넘어지게 하는 것',
  'subtilty': '간교함, 교묘함',
  'sware': '맹세하였다 (고어, swear의 과거형)',
  'sycomore': '뽕나무, 돌무화과나무',
  'tabret': '소고, 작은 북',
  'tabrets': '소고들, 작은 북들',
  'threshingfloor': '타작마당',
  'thereunto': '그것에, 그곳에',
  'thyself': '너 자신 (고어)',
  'traffick': '무역, 거래; 무역하다',
  'twoedged': '양날의, 두 날을 가진',
  'uncircumcised': '할례받지 않은',
  'uncircumcision': '무할례, 할례받지 않은 상태',
  'undersetters': '받침대, 아래를 받치는 지지물',
  'vail': '베일, 너울; 가리다',
  'whereas': '~인 반면에; ~이므로',
  'whereby': '그것으로, 그로 말미암아',
  'whereof': '그것의, 그것에 관하여',
  'whereon': '그 위에, 그것 위에',
  'whereunto': '그곳으로, 그것에',
  'whereupon': '그 위에; 그러자, 그 결과',
  'wherewith': '그것으로, 그것을 가지고',
  'whithersoever': '어디로 가든지, 어디든지',
  'whomsoever': '누구든지, 누구를 막론하고',
  'whoso': '누구든지, ~하는 자',
  'whosoever': '누구든지, ~하는 자는 누구나',
  'wist': '알았다 (고어, know의 과거형)',
  'wreathen': '땋은, 꼬아 만든',
  'withholden': '막은, 금한, 억제한',
  'workmen': '일꾼들, 기술자들',
  'watchmen': '파수꾼들, 경비하는 사람들',
  'abilene': '아빌레네(성경 지명)',
  'acts': '사도행전',
  'adalia': '아달리야(성경 인명)',
  'agee': '아게(성경 인명)',
  'agrippa': '아그립바 왕',
  'ahab': '아합 왕',
  'ain': '아인(성경 지명)',
  'akan': '아간(성경 인명)',
  'antioch': '안디옥',
  'ara': '아라(성경 인명)',
  'aram': '아람',
  'ararat': '아라랏 산',
  'aristarchus': '아리스다고',
  'artaxerxes': '아닥사스다 왕',
  'ashur': '아스훌(성경 인명)',
  'assur': '앗수르',
  'berit': '브릿(언약을 뜻하는 이름의 일부)',
  'berites': '베림 사람들 또는 베림 지역',
  'berith': '브릿, 언약',
  'bithynia': '비두니아',
  'cappadocia': '가바도기아',
  'cesar': '가이사(로마 황제의 칭호)',
  'chios': '기오',
  'clamour': '떠드는 소리, 소란',
  'change': '바꾸다, 변하다; 변화',
  'dagon': '다곤(블레셋의 신)',
  'demetrius': '데메드리오',
  'dura': '두라 평지',
  'elul': '엘룰월(히브리력 여섯째 달)',
  'ephah': '에바(성경 인명 또는 부피 단위)',
  'exorcist': '축귀자, 악귀를 쫓는 사람',
  'favour': '은혜, 호의; 좋아하다',
  'foe': '적, 원수',
  'gaddi': '갓디',
  'gaius': '가이오',
  'gadites': '갓 자손, 갓 지파 사람들',
  'gimel': '기멜(히브리 문자)',
  'golan': '골란',
  'gittite': '가드 사람',
  'gunite': '구니 가족에 속한 사람',
  'heth': '헷(성경 인명 또는 히브리 문자)',
  'hillel': '힐렐',
  'hin': '힌(고대 액체 부피 단위)',
  'issachar': '잇사갈',
  'jehoash': '요아스(성경 인명)',
  'jezreelite': '이스르엘 사람',
  'jetheth': '여뎃',
  'joppa': '욥바',
  'laban': '라반',
  'lest': '~하지 않도록, ~할까 두려워',
  'libyan': '리비아 사람',
  'line': '줄, 선; 계통',
  'live': '살다, 생존하다; 살아 있는',
  'make': '만들다, 행하다',
  'marry': '결혼하다',
  'medan': '므단',
  'mem': '멤(히브리 문자)',
  'memphis': '놉, 멤피스',
  'mere': '작은 못, 연못; 단지 ~에 불과한',
  'merodach': '므로닥(바벨론의 신)',
  'mite': '렙돈, 매우 작은 동전',
  'molech': '몰렉',
  'moloch': '몰록',
  'neginoth': '현악, 현악기에 맞춘 노래',
  'nebo': '느보',
  'nergal': '네르갈',
  'nisan': '니산월(히브리력 첫째 달)',
  'oni': '오니(베노니 이름의 일부, 슬픔)',
  'ono': '오노',
  'pace': '걸음, 보폭; 걷다',
  'peleth': '벨렛',
  'pelethites': '블렛 사람들',
  'philistia': '블레셋',
  'pisgah': '비스가 산',
  'phylactery': '경문, 성구함',
  'pinon': '비논',
  'pontus': '본도',
  'pretorium': '브라이도리온, 총독 관저',
  'resh': '레쉬(히브리 문자)',
  'shakeh': '랍사게(앗수르의 고위 관직명)',
  'roe': '노루, 암사슴; 어란',
  'roi': '로이(브엘라해로이 지명의 일부)',
  'salah': '셀라(성경 인명)',
  'samaria': '사마리아',
  'sardis': '사데',
  'sennacherib': '산헤립',
  'shan': '산(벧산 지명의 일부)',
  'shedder': '피를 흘리는 자, 살인자',
  'shema': '세마',
  'shiloh': '실로',
  'shisha': '시사',
  'shittah': '싯다(성경 지명)',
  'shittim': '조각목; 싯딤',
  'shua': '수아',
  'simon': '시몬',
  'sivan': '시완월(히브리력 셋째 달)',
  'slanderously': '비방하여, 중상하여',
  'smyrna': '서머나',
  'sorceress': '무녀, 여자 마술사',
  'stachys': '스다구',
  'stuck': '꽂힌, 박힌; 달라붙은',
  'superscription': '새긴 글, 명문',
  'susah': '수사(성경 지명의 일부)',
  'susanna': '수산나',
  'tammuz': '담무스',
  'tanach': '다아낙',
  'tentmaker': '천막을 만드는 사람',
  'teth': '테트(히브리 문자)',
  'thessalonica': '데살로니가',
  'tychicus': '두기고(바울의 동역자)',
  'tyrus': '두로',
  'tyrannus': '두란노',
  'ummah': '움마',
  'ur': '우르',
  'urias': '우리아',
  'vulture': '독수리류, 솔개',
  'wilfully': '고의로, 일부러',
  'zarhites': '세라 자손',
  'zeeb': '스엡(미디안의 방백)',
  'ziph': '십(유다의 성읍과 광야)',
  'beelzebub': '바알세불',
  'broider': '수놓다, 자수하다',
  'chaldee': '갈대아 사람 또는 갈대아 말',
  'colour': '색, 빛깔',
  'coulter': '보습, 쟁기날',
  'crossway': '사거리, 갈림길',
  'defence': '보호, 방어; 요새화하다',
  'emulation': '시기, 경쟁심',
  'enquire': '묻다, 알아보다',
  'ewe': '암양',
  'fresher': '더 신선한, 더 생기 있고 연한',
  'hindermost': '가장 뒤쪽의',
  'ho': '이봐, 여보게(부르는 말)',
  'hundredfold': '백 배',
  'inclose': '둘러싸다, 에워싸다',
  'inwards': '내장; 안쪽으로',
  'muse': '묵상하다, 깊이 생각하다',
  'nebuchadrezzar': '느부갓네살 왕',
  'nigh': '가까이, 가까운',
  'nitre': '소다, 탄산나트륨',
  'offence': '죄, 거리낌; 실족하게 하는 것',
  'oftentimes': '자주, 여러 번',
  'peaceably': '평화롭게, 화목하게',
  'phenicia': '베니게',
  'practise': '행하다, 실행하다',
  'prise': '들추다, 억지로 열다',
  'quietness': '평온, 안식',
  'rameses': '라암세스',
  'see': '보다, 알다',
  'sere': '마른, 시든',
  'serjeant': '관원, 하급 관리',
  'sherd': '도기 조각, 깨진 조각',
  'shew': '보이다, 지시하다',
  'sion': '시온',
  'skilful': '능숙한, 익숙한',
  'stubble': '그루터기, 곡초',
  'timbrel': '소고, 탬버린',
  'trade': '거래하다, 장사하다',
  'twain': '둘, 두 사람 또는 두 가지',
  'uttermost': '가장 끝의; 지극한',
  'valour': '용맹, 용기',
  'vapour': '안개, 수증기',
};

/// WordNet이 KJV 활용형을 우연히 같은 철자인 다른 표제어로 해석하는 경우.
const kjvWordRootOverrides = <String, String>{
  'changes': 'change',
  'changest': 'change',
  'changeth': 'change',
  'foes': 'foe',
  'lest': 'lest',
  'lines': 'line',
  'lived': 'live',
  'livest': 'live',
  'liveth': 'live',
  'makest': 'make',
  'maketh': 'make',
  'marrieth': 'marry',
  'mites': 'mite',
  'paces': 'pace',
  'peleth': 'peleth',
  'roes': 'roe',
  'urias': 'urias',
  'vultures': 'vulture',
  'jetheth': 'jetheth',
  'ewes': 'ewe',
  'mused': 'muse',
  'seest': 'see',
  'seeth': 'see',
  'traded': 'trade',
};

/// 이미 생성된 이전 사전의 잘못된 표제어를 정상 표제어로 병합할 때 사용한다.
const generatedRootCorrections = <String, String>{
  'chang': 'change',
  'fo': 'foe',
  'le': 'lest',
  'lin': 'line',
  'liv': 'live',
  'mak': 'make',
  'marri': 'marry',
  'mit': 'mite',
  'pac': 'pace',
  'pel': 'peleth',
  'ro': 'roe',
  'uria': 'urias',
  'vultur': 'vulture',
  'jeth': 'jetheth',
  'ew': 'ewe',
  'mus': 'muse',
  'se': 'see',
  'trad': 'trade',
};
