const bibleKoreanSupplement = <String, String>{
  'abilene': '아빌레네(성경 지명)',
  'acts': '사도행전',
  'adalia': '아달리야(성경 인명)',
  'agee': '아게(성경 인명)',
  'agrippa': '아그립바 왕',
  'ahab': '아합 왕',
  'ain': '아인(성경 지명)',
  'akan': '아간(성경 인명)',
  'antioch': '안디옥',
  'ara': '아라(성경 인명)',
  'aram': '아람',
  'ararat': '아라랏 산',
  'aristarchus': '아리스다고',
  'artaxerxes': '아닥사스다 왕',
  'ashur': '아스훌(성경 인명)',
  'assur': '앗수르',
  'berit': '브릿(언약을 뜻하는 이름의 일부)',
  'berites': '베림 사람들 또는 베림 지역',
  'berith': '브릿, 언약',
  'bithynia': '비두니아',
  'cappadocia': '가바도기아',
  'chios': '기오',
  'clamour': '떠드는 소리, 소란',
  'change': '바꾸다, 변하다; 변화',
  'dagon': '다곤(블레셋의 신)',
  'demetrius': '데메드리오',
  'dura': '두라 평지',
  'elul': '엘룰월(히브리력 여섯째 달)',
  'ephah': '에바(성경 인명 또는 부피 단위)',
  'exorcist': '축귀자, 악귀를 쫓는 사람',
  'favour': '은혜, 호의; 좋아하다',
  'foe': '적, 원수',
  'gaddi': '갓디',
  'gaius': '가이오',
  'gimel': '기멜(히브리 문자)',
  'golan': '골란',
  'gunite': '구니 가족에 속한 사람',
  'heth': '헷(성경 인명 또는 히브리 문자)',
  'hillel': '힐렐',
  'hin': '힌(고대 액체 부피 단위)',
  'issachar': '잇사갈',
  'jetheth': '여뎃',
  'joppa': '욥바',
  'laban': '라반',
  'lest': '~하지 않도록, ~할까 두려워',
  'libyan': '리비아 사람',
  'line': '줄, 선; 계통',
  'live': '살다, 생존하다; 살아 있는',
  'make': '만들다, 행하다',
  'marry': '결혼하다',
  'medan': '므단',
  'mem': '멤(히브리 문자)',
  'memphis': '놉, 멤피스',
  'mere': '작은 못, 연못; 단지 ~에 불과한',
  'merodach': '므로닥(바벨론의 신)',
  'mite': '렙돈, 매우 작은 동전',
  'molech': '몰렉',
  'moloch': '몰록',
  'nebo': '느보',
  'nergal': '네르갈',
  'nisan': '니산월(히브리력 첫째 달)',
  'oni': '오니(베노니 이름의 일부, 슬픔)',
  'ono': '오노',
  'pace': '걸음, 보폭; 걷다',
  'peleth': '벨렛',
  'philistia': '블레셋',
  'phylactery': '경문, 성구함',
  'pinon': '비논',
  'pontus': '본도',
  'pretorium': '브라이도리온, 총독 관저',
  'resh': '레쉬(히브리 문자)',
  'roe': '노루, 암사슴; 어란',
  'roi': '로이(브엘라해로이 지명의 일부)',
  'salah': '셀라(성경 인명)',
  'samaria': '사마리아',
  'sardis': '사데',
  'sennacherib': '산헤립',
  'shan': '산(벧산 지명의 일부)',
  'shedder': '피를 흘리는 자, 살인자',
  'shema': '세마',
  'shiloh': '실로',
  'shisha': '시사',
  'shittah': '싯다(성경 지명)',
  'shittim': '조각목; 싯딤',
  'shua': '수아',
  'simon': '시몬',
  'sivan': '시완월(히브리력 셋째 달)',
  'slanderously': '비방하여, 중상하여',
  'smyrna': '서머나',
  'sorceress': '무녀, 여자 마술사',
  'stachys': '스다구',
  'stuck': '꽂힌, 박힌; 달라붙은',
  'superscription': '새긴 글, 명문',
  'susah': '수사(성경 지명의 일부)',
  'susanna': '수산나',
  'tammuz': '담무스',
  'tanach': '다아낙',
  'tentmaker': '천막을 만드는 사람',
  'teth': '테트(히브리 문자)',
  'thessalonica': '데살로니가',
  'tyrannus': '두란노',
  'ummah': '움마',
  'ur': '우르',
  'urias': '우리아',
  'vulture': '독수리류, 솔개',
  'wilfully': '고의로, 일부러',
  'beelzebub': '바알세불',
  'broider': '수놓다, 자수하다',
  'chaldee': '갈대아 사람 또는 갈대아 말',
  'colour': '색, 빛깔',
  'coulter': '보습, 쟁기날',
  'crossway': '사거리, 갈림길',
  'defence': '보호, 방어; 요새화하다',
  'emulation': '시기, 경쟁심',
  'enquire': '묻다, 알아보다',
  'ewe': '암양',
  'fresher': '더 신선한, 더 생기 있고 연한',
  'hindermost': '가장 뒤쪽의',
  'ho': '이봐, 여보게(부르는 말)',
  'hundredfold': '백 배',
  'inclose': '둘러싸다, 에워싸다',
  'inwards': '내장; 안쪽으로',
  'muse': '묵상하다, 깊이 생각하다',
  'nebuchadrezzar': '느부갓네살 왕',
  'nigh': '가까이, 가까운',
  'nitre': '소다, 탄산나트륨',
  'offence': '죄, 거리낌; 실족하게 하는 것',
  'oftentimes': '자주, 여러 번',
  'peaceably': '평화롭게, 화목하게',
  'phenicia': '베니게',
  'practise': '행하다, 실행하다',
  'prise': '들추다, 억지로 열다',
  'quietness': '평온, 안식',
  'rameses': '라암세스',
  'see': '보다, 알다',
  'sere': '마른, 시든',
  'serjeant': '관원, 하급 관리',
  'sherd': '도기 조각, 깨진 조각',
  'shew': '보이다, 지시하다',
  'sion': '시온',
  'skilful': '능숙한, 익숙한',
  'stubble': '그루터기, 곡초',
  'timbrel': '소고, 탬버린',
  'trade': '거래하다, 장사하다',
  'twain': '둘, 두 사람 또는 두 가지',
  'uttermost': '가장 끝의; 지극한',
  'valour': '용맹, 용기',
  'vapour': '안개, 수증기',
};

/// WordNet이 KJV 활용형을 우연히 같은 철자인 다른 표제어로 해석하는 경우.
const kjvWordRootOverrides = <String, String>{
  'changes': 'change',
  'changest': 'change',
  'changeth': 'change',
  'foes': 'foe',
  'lest': 'lest',
  'lines': 'line',
  'lived': 'live',
  'livest': 'live',
  'liveth': 'live',
  'makest': 'make',
  'maketh': 'make',
  'marrieth': 'marry',
  'mites': 'mite',
  'paces': 'pace',
  'peleth': 'peleth',
  'roes': 'roe',
  'urias': 'urias',
  'vultures': 'vulture',
  'jetheth': 'jetheth',
  'ewes': 'ewe',
  'mused': 'muse',
  'seest': 'see',
  'seeth': 'see',
  'traded': 'trade',
};

/// 이미 생성된 이전 사전의 잘못된 표제어를 정상 표제어로 병합할 때 사용한다.
const generatedRootCorrections = <String, String>{
  'chang': 'change',
  'fo': 'foe',
  'le': 'lest',
  'lin': 'line',
  'liv': 'live',
  'mak': 'make',
  'marri': 'marry',
  'mit': 'mite',
  'pac': 'pace',
  'pel': 'peleth',
  'ro': 'roe',
  'uria': 'urias',
  'vultur': 'vulture',
  'jeth': 'jetheth',
  'ew': 'ewe',
  'mus': 'muse',
  'se': 'see',
  'trad': 'trade',
};
