/// Reviewed Korean meanings for KJV terms that are not reliably covered by
/// general-purpose bilingual dictionaries. These values replace the old
/// parallel-verse token guesses.
const kjvContextualKoreanCorrections = <String, String>{
  // KJV vocabulary, compounds, and historical inflections.
  'aforehand': '미리, 사전에',
  'almsdeeds': '구제 행위, 자선을 베푸는 일',
  'almug': '백단목, 성전 건축에 쓰인 향기로운 목재',
  'ambassage': '사절단, 사신의 임무',
  'amongst': '~가운데에, ~사이에',
  'asswage': '가라앉히다, 누그러뜨리다',
  'asswaged': '가라앉은, 누그러진',
  'attent': '주의 깊은, 유의하는',
  'aul': '송곳',
  'backbitings': '험담, 뒤에서 비방하는 말',
  'bakemeats': '구운 음식, 빵이나 과자류',
  'barnfloor': '타작마당',
  'bishoprick': '감독의 직분, 감독 관할구',
  'bondservant': '종, 속박된 신분의 하인',
  'bondservice': '종살이, 노예로 섬기는 일',
  'bridechamber': '혼인방, 신랑과 하객이 모이는 곳',
  'bringers': '가져오는 자들, 인도하는 자들',
  'broided': '땋은, 장식으로 엮은',
  'brokenfooted': '발이 부러진, 발에 장애가 있는',
  'brokenhanded': '손이 부러진, 손에 장애가 있는',
  'buryingplace': '매장지, 묘지',
  'calkers': '배의 틈을 메우는 기술자들',
  'camphire': '고벨화, 헤나 꽃',
  'chapt': '갈라진, 말라서 튼',
  'chargedst': '명령하였다, 맡겼다 (고어)',
  'chesnut': '신풍나무, 버즘나무',
  'chode': '다투었다, 꾸짖었다 (chide의 옛 과거형)',
  'chrysoprasus': '녹옥수, 황록색 보석',
  'cieling': '천장, 널판으로 입힌 천장',
  'clift': '바위 틈, 갈라진 절벽',
  'clifts': '바위 틈들, 갈라진 절벽들',
  'clovenfooted': '굽이 갈라진',
  'cornfloor': '곡식을 떠는 타작마당',
  'corrupters': '부패시키는 자들, 타락한 자들',
  'couchingplace': '눕는 곳, 쉬는 자리',
  'covenantbreakers': '언약을 깨뜨리는 자들, 신의를 저버리는 자들',
  'criest': '부르짖는다, 외친다 (고어)',
  'crookbackt': '등이 굽은, 곱사등인',
  'cuckow': '뻐꾸기류의 새',
  'cummin': '소회향, 커민',
  'cursedst': '저주하였다 (고어)',
  'cursings': '저주의 말들',
  'deceivings': '속임수들, 기만하는 행위',
  'defiledst': '더럽혔다, 부정하게 하였다 (고어)',
  'desiredst': '바랐다, 원하였다 (고어)',
  'despisers': '멸시하는 자들',
  'diggedst': '팠다 (고어)',
  'disputings': '논쟁들, 다툼',
  'downsitting': '앉음, 앉아 있는 때',
  'driedst': '말렸다, 마르게 하였다 (고어)',
  'dureth': '지속된다, 견딘다 (고어)',
  'dwellingplace': '거처, 사는 곳',
  'emptiers': '비우는 자들, 약탈자들',
  'endamage': '손해를 입히다, 해치다',
  'engraven': '새긴, 조각한',
  'eveningtide': '저녁때, 해 질 무렵',
  'evilfavouredness': '흉한 외모, 보기 흉한 상태',
  'executedst': '시행하였다, 집행하였다 (고어)',
  'eyesalve': '눈에 바르는 약, 안약',
  'fallowdeer': '다마사슴, 노루 종류',
  'fatfleshed': '살이 찐, 살진',
  'feedingplace': '먹이를 먹는 곳, 목초지',
  'fellowcitizens': '동료 시민들, 같은 나라 백성',
  'fellowdisciples': '동료 제자들',
  'fellowheirs': '함께 유업을 이을 자들, 공동 상속자들',
  'fellowhelper': '함께 돕는 동역자',
  'fellowhelpers': '함께 돕는 동역자들',
  'fellowlabourer': '함께 수고하는 동역자',
  'fellowlabourers': '함께 수고하는 동역자들',
  'fellowprisoner': '함께 갇힌 사람',
  'fellowprisoners': '함께 갇힌 사람들',
  'fellowsoldier': '함께 싸우는 군사, 전우',
  'fellowworkers': '함께 일하는 동역자들',
  'fetcht': '가져왔다, 데려왔다 (fetch의 옛 과거형)',
  'firstbegotten': '처음 난 자, 맏아들',
  'firstfruit': '첫 열매, 처음 익은 소산',
  'fishpools': '물고기를 기르는 못들, 양어장',
  'folden': '접힌, 서로 얽힌',
  'forbare': '삼갔다, 그만두었다 (forbear의 옛 과거형)',
  'forborn': '참아 온, 삼가 온',
  'forsomuch': '~이므로, ~인 까닭에',
  'fryingpan': '번철, 프라이팬',
  'garlick': '마늘',
  'gazingstock': '구경거리, 공개적인 조롱거리',
  'gier': '독수리류의 새',
  'glede': '솔개류의 맹금',
  'gloriest': '자랑한다, 기뻐한다 (고어)',
  'graff': '접붙이다',
  'grapegatherer': '포도를 거두는 사람',
  'grapegatherers': '포도를 거두는 사람들',
  'grapegleanings': '포도를 거둔 뒤 남은 이삭',
  'graveclothes': '시신을 싸는 수의와 베',
  'gravings': '새긴 무늬, 조각물',
  'groanings': '신음, 탄식',
  'guestchamber': '손님방, 객실',
  'handstaves': '손에 드는 지팡이 또는 몽둥이',
  'handywork': '손으로 만든 작품, 솜씨',
  'havock': '파괴, 큰 황폐; 마구 파괴하다',
  'herdman': '목자, 가축을 돌보는 사람',
  'heretick': '이단자, 그릇된 교훈을 고집하는 사람',
  'holyday': '거룩한 날, 절기',
  'horseleach': '거머리',
  'hosen': '바지나 각반 형태의 옷',
  'hough': '말의 뒷다리 힘줄을 끊다',
  'houghed': '뒷다리 힘줄이 끊긴',
  'humbledst': '낮추었다, 겸손하게 하였다 (고어)',
  'hungerbitten': '굶주림에 시달린',
  'inclosings': '보석을 물리는 테두리, 세공 틀',
  'inhabiters': '거주민들, 사는 자들',
  'intreaties': '간청, 탄원',
  'intreaty': '간청, 탄원',
  'jeoparded': '위험에 내맡겼다',
  'justle': '서로 밀치다, 부딪치다',
  'laidst': '두었다, 놓았다 (고어)',
  'leanfleshed': '살이 여윈, 야윈',
  'lign': '알로에 향목, 향기로운 목재',
  'ligure': '호박 또는 황갈색 보석',
  'loaden': '짐을 실은, 무거운 짐을 진',
  'longwinged': '날개가 긴',
  'lovedst': '사랑하였다 (고어)',
  'lowring': '흐린, 찌푸린',
  'lunatick': '간질로 고통받는 사람, 발작하는 사람',
  'magnifical': '장엄한, 매우 훌륭한',
  'maneh': '마네, 고대의 무게와 화폐 단위',
  'masterbuilder': '수석 건축자, 책임 건축가',
  'menpleasers': '사람의 환심만 사려는 자들',
  'menstealers': '사람을 납치하여 파는 자들',
  'mercyseat': '속죄소, 언약궤를 덮는 금 덮개',
  'merryhearted': '마음이 즐거운',
  'meteyard': '측량하는 자, 측량 기준',
  'mixt': '섞인, 혼합한',
  'moneychangers': '환전상들, 돈 바꾸는 사람들',
  'movedst': '움직였다, 격동시켰다 (고어)',
  'mowings': '풀을 벤 뒤 다시 돋는 새싹',
  'multipliedst': '번성하게 하였다, 크게 늘렸다 (고어)',
  'neesings': '재채기, 콧김',
  'neighings': '말의 울음소리들',
  'offscouring': '찌꺼기, 버림받아 천대받는 것',
  'oliveyard': '감람원, 올리브 과수원',
  'omer': '오멜, 고대 히브리의 곡식 부피 단위',
  'omers': '오멜 단위들',
  'onycha': '소합향, 향 재료로 쓰인 향기로운 물질',
  'ospray': '물수리',
  'pluckt': '뽑았다, 뜯었다 (pluck의 옛 과거형)',
  'pransing': '말이 발을 높이 들며 뛰는 동작',
  'pransings': '말들이 발을 높이 들며 뛰는 동작들',
  'preparedst': '준비하였다 (고어)',
  'pressfat': '포도즙을 받아 모으는 통',
  'promisedst': '약속하였다 (고어)',
  'prophesyings': '예언들, 예언하는 일',
  'provokedst': '노하게 하였다, 격분시켰다 (고어)',
  'pruninghooks': '낫, 가지치기용 갈고리',
  'publick': '공개적인, 공공의 (옛 철자)',
  'publickly': '공개적으로 (옛 철자)',
  'purtenance': '내장, 몸속 기관',
  'putrifying': '곪아 썩어 가는',
  'pygarg': '들염소 또는 영양 종류',
  'receivedst': '받았다 (고어)',
  'refusedst': '거절하였다 (고어)',
  'repentings': '뉘우침, 긍휼히 여기려는 마음',
  'repliest': '대답한다, 말대꾸한다 (고어)',
  'restingplace': '안식처, 쉬는 곳',
  'revellings': '방탕한 잔치와 흥청거림',
  'revilers': '욕하고 비방하는 자들',
  'revilings': '욕설과 비방',
  'revolters': '반역자들, 배반한 자들',
  'rie': '호밀',
  'sacrificedst': '제사로 드렸다 (고어)',
  'saltpits': '소금 구덩이, 염전',
  'satisfiest': '만족시킨다, 채워 준다 (고어)',
  'scourgings': '채찍질, 매질',
  'seatward': '좌석 또는 속죄소 쪽을 향하여',
  'selfwill': '제 고집, 자기 뜻대로 하려는 마음',
  'servedst': '섬겼다, 봉사하였다 (고어)',
  'shapen': '형성된, 빚어진',
  'sheepshearers': '양털 깎는 사람들',
  'shoelatchet': '신발 끈',
  'silverlings': '은화, 은으로 된 돈',
  'sith': '~이므로, ~인 까닭에 (고어)',
  'sixscore': '백이십, 120',
  'skippedst': '기뻐 뛰었다 (고어)',
  'slimepits': '역청 구덩이들',
  'slingstones': '물매로 던지는 돌들',
  'slumberings': '얕은 잠, 졸음',
  'smiters': '때리는 자들, 치는 자들',
  'snuffdishes': '등잔 심지 찌꺼기를 담는 그릇들',
  'sodering': '납땜, 금속을 이어 붙이는 일',
  'spunge': '해면, 스펀지 (옛 철자)',
  'stonesquarers': '돌을 다듬는 석공들',
  'stript': '벗겼다, 빼앗았다 (strip의 옛 과거형)',
  'strowed': '흩뿌렸다 (strew의 옛 과거형)',
  'stumblingstone': '걸림돌, 넘어지게 하는 돌',
  'subduedst': '정복하였다, 굴복시켰다 (고어)',
  'subtil': '간교한, 교묘한 (옛 철자)',
  'subtilly': '교묘하게, 은밀하게 (옛 철자)',
  'surmisings': '억측, 악한 의심',
  'swaddlingband': '강보, 갓난아이를 싸는 천',
  'sweetsmelling': '향기로운',
  'sycamine': '뽕나무 종류',
  'tabering': '가슴을 두드리며 슬퍼하는',
  'tarriest': '지체한다, 머뭇거린다 (고어)',
  'teraphim': '드라빔, 집안에서 섬기던 우상',
  'terrifiest': '두렵게 한다, 놀라게 한다 (고어)',
  'testifiedst': '증언하였다, 경고하였다 (고어)',
  'thirtyfold': '삼십 배',
  'thitherward': '그쪽으로, 그곳을 향하여',
  'threshingplace': '타작마당',
  'thyine': '향나무의 한 종류, 두야나무로 만든',
  'tossings': '뒤척임, 이리저리 흔들림',
  'townclerk': '서기장, 도시의 행정 책임자',
  'triest': '시험한다, 살핀다 (고어)',
  'troubledst': '흐리게 하였다, 어지럽혔다 (고어)',
  'trucebreakers': '화해하지 않는 자들, 약속을 깨뜨리는 자들',
  'unblameable': '책망할 것이 없는',
  'unblameably': '책망할 것이 없게',
  'uncondemned': '재판이나 유죄 판결을 받지 않은',
  'uncorruptness': '부패하지 않음, 순전함',
  'unmoveable': '움직이지 않는, 흔들리지 않는',
  'unperfect': '아직 완전한 형체를 이루지 않은',
  'unrebukeable': '책망할 것이 없는',
  'unreproveable': '흠잡거나 책망할 것이 없는',
  'unskilful': '익숙하지 않은, 미숙한',
  'untaken': '제거되지 않은, 걷히지 않은',
  'unwalled': '성벽이 없는',
  'unwashen': '씻지 않은',
  'upholden': '붙들어 준, 지탱한',
  'villany': '악행, 사악함',
  'washpot': '씻는 대야, 목욕통',
  'waterpot': '물을 담는 항아리',
  'waterpots': '물을 담는 항아리들',
  'watersprings': '샘물, 물이 솟는 샘들',
  'wellfavoured': '용모가 아름다운, 보기 좋은',
  'whereabout': '~에 관하여, 그 일을 위하여',
  'winterhouse': '겨울 별궁, 겨울에 머무는 집',
  'womenservants': '여종들, 여자 하인들',

  // Biblical names, places, peoples, titles, and hyphenated name elements.
  'abarim': '아바림(모압 동쪽의 산지와 지역)',
  'abez': '에베스(잇사갈 지파의 성읍)',
  'achaz': '아하스(유다 왕)',
  'acrabbim': '아그랍빔(에돔 경계의 비탈)',
  'adan': '아단(느부사라단의 이름 요소)',
  'addar': '앗달 또는 하살앗달(성경 지명)',
  'albon': '알본(아비알본의 이름 요소)',
  'ammah': '암마 산(기브온 근처의 산)',
  'ammi': '암미(벤암미와 로암미에 쓰인 이름 요소)',
  'amminadib': '귀한 백성, 또는 암미나딥(아가 6:12의 표현)',
  'amramites': '아므람 가족, 아므람 자손',
  'anath': '아낫(벧아낫 등 성경 이름의 요소)',
  'anoth': '아놋(벧아놋의 이름 요소)',
  'aphrah': '아브라(베들레아브라로 번역된 성경 지명)',
  'arabah': '아라바(요단 골짜기와 사해 주변 지역)',
  'arba': '아르바(기럇아르바의 이름 요소)',
  'arbathite': '아르바 사람',
  'arbel': '아르벨(벧아르벨의 이름 요소)',
  'arbite': '아랍 사람',
  'archevites': '아렉 사람들',
  'archite': '아렉 사람',
  'arim': '여아림(기럇여아림의 이름 요소)',
  'arkite': '알가 족속 사람',
  'ashdoth': '비스가 산록(아스돗비스가로 불린 비탈)',
  'ashdothites': '아스돗 사람들',
  'asherites': '아셀 지파 사람들',
  'ashterathite': '아스드랏 사람',
  'asuppim': '곳간, 성전 창고',
  'atha': '우리 주여 오시옵소서(마라나타의 뒷부분)',
  'aven': '아웬(벧아웬 등 성경 지명의 요소)',
  'avites': '아위 사람들',
  'azaz': '아사스(성경 인명)',
  'azotus': '아소도, 아스돗의 헬라식 이름',
  'azzah': '가사(블레셋 성읍)',
  'baca': '눈물 골짜기(시편 84편의 지명 또는 상징)',
  'bachuth': '바굿(알론바굿의 이름 요소, 통곡이라는 뜻)',
  'baladan': '발라단(바벨론 왕가의 인명)',
  'barah': '바라(성경 이름에 쓰인 고유명사 요소)',
  'barnea': '바네아(가데스바네아의 이름 요소)',
  'baz': '바스(마헬살랄하스바스의 이름 요소)',
  'beerothites': '브에롯 사람들',
  'bekah': '베가, 반 세겔에 해당하는 무게 단위',
  'benob': '브놉(이스비브놉의 이름 요소)',
  'benoth': '브놋(숙곳브놋의 이름 요소)',
  'berak': '브락(브네브락의 이름 요소)',
  'beseth': '베셋(비베셋의 이름 요소)',
  'bezek': '베섹(가나안의 성읍)',
  'birei': '비리(벧비리의 이름 요소)',
  'bizjothjah': '비스요댜(유다 지파의 성읍)',
  'booz': '보아스(성경 인명)',
  'boznai': '보스내(스달보스내의 이름 요소)',
  'buzite': '부스 사람',
  'caph': '카프, 히브리 문자의 열한째 글자',
  'caphtor': '갑돌(블레셋 사람들의 기원지)',
  'caphtorims': '갑돌 사람들',
  'chabod': '가봇(이가봇의 이름 요소, 영광이라는 뜻)',
  'chephar': '그발(그발암모니의 이름 요소)',
  'cherethites': '그렛 사람들, 다윗의 호위 부대',
  'cheth': '헤트, 히브리 문자의 여덟째 글자',
  'chezib': '거십(유다 지역의 성읍)',
  'chor': '고라산(성경 지명)',
  'chun': '군(하닷에셀의 성읍)',
  'cleopas': '글로바(예수의 부활 길에 만난 제자)',
  'cleophas': '글로바(십자가 곁 마리아의 남편)',
  'corinthus': '고린도(그리스의 도시)',
  'crescens': '그레스게(바울의 동역자)',
  'cumi': '일어나라(달리다굼에 쓰인 아람어)',
  'cuth': '굿(앗수르 제국의 지역 또는 민족)',
  'dammim': '담밈(에베스담밈 등 지명의 요소, 피라는 뜻)',
  'dekar': '데겔(벤데겔의 이름 요소)',
  'diblathaim': '디블라다임(알몬디블라다임의 이름 요소)',
  'eduth': '에둣, 증거라는 뜻의 시편 곡명 요소',
  'eglaim': '에글라임(모압의 지명)',
  'elem': '엘렘(요낫엘렘르호김의 시편 곡명 요소)',
  'elohe': '엘로헤(엘엘로헤이스라엘의 이름 요소, 하나님이라는 뜻)',
  'emek': '에멕(벧에멕의 이름 요소)',
  'enan': '에난(성경 인명)',
  'enflaming': '욕정에 불타는, 음욕을 품는',
  'enviest': '시기한다 (고어)',
  'envyings': '시기와 질투',
  'ephes': '에베스(에베스담밈의 이름 요소)',
  'ephraimite': '에브라임 사람',
  'ephraimites': '에브라임 지파 사람들',
  'ephrain': '에브론(에브라임 산지의 성읍)',
  'ephrathites': '에브랏 사람들, 베들레헴 사람들',
  'esar': '에살(에살핫돈의 이름 요소)',
  'esh': '에스(에스바알의 이름 요소)',
  'eshkalonites': '아스글론 사람들',
  'eshtaulites': '에스다올 사람들',
  'euroclydon': '유라굴로, 지중해의 강한 북동풍',
  'eutychus': '유두고(바울의 설교 중 창에서 떨어진 청년)',
  'ezel': '에셀 바위(다윗과 요나단이 약속한 장소)',
  'ezer': '에셀(성경 인명)',
  'eznite': '에센 사람',
  'ezrahite': '에스라 사람 또는 예스라 사람',
  'ezrite': '아비에셀 사람',
  'ezrites': '아비에셀 사람들',
  'fortunatus': '브드나도(고린도 교회의 신자)',
  'gadarenes': '거라사인 또는 가다라 지방 사람들',
  'gaddah': '갓다(하살갓다의 이름 요소)',
  'gadite': '갓 지파 사람',
  'gammadims': '감마딤 사람들, 두로 성벽을 지킨 용사들',
  'gamul': '가물(제사장 가문의 인명)',
  'gannim': '간님(엔간님의 이름 요소)',
  'gazathites': '가사 사람들',
  'gazites': '가사 사람들',
  'geber': '게벨(벤게벨 등의 이름 요소)',
  'gedi': '게디(엔게디의 이름 요소)',
  'gergesenes': '가다라 또는 거라사 지방 사람들',
  'geshurites': '그술 사람들',
  'gittah': '가드(가드헤벨의 이름 요소)',
  'haammonai': '암모니(그발암모니의 이름 요소)',
  'haccerem': '학게렘(벧학게렘의 이름 요소)',
  'hadad': '하닷(에돔 왕과 아람 신의 이름)',
  'haddah': '핫다(엔핫다의 이름 요소)',
  'haddon': '핫돈(에살핫돈의 이름 요소)',
  'hagerite': '하갈 사람',
  'hagidgad': '하깃갓(홀하깃갓의 이름 요소)',
  'hahiroth': '하히롯(비하히롯의 이름 요소)',
  'hakkore': '학고레(엔학고레의 이름 요소, 부르짖는 자의 샘)',
  'hamah': '하마(성경 이름에 쓰인 고유명사 요소)',
  'hammahlekoth': '하마느곳(셀라하마느곳의 이름 요소)',
  'hammelech': '왕 또는 왕의 아들에 쓰인 히브리어 표현',
  'hamon': '하몬(바알하몬과 하몬곡 등의 이름 요소)',
  'hanan': '하난(성경 인명)',
  'happuch': '합북(게렌합북의 이름 요소)',
  'hareseth': '하레셋(길하레셋의 이름 요소)',
  'haresh': '하레셋(길하레셋의 다른 철자)',
  'haresha': '하레사(성경 인명 또는 지명 요소)',
  'harsa': '하르사(성전 봉사자 가문의 이름)',
  'hattaavah': '핫다아와(기브롯핫다아와의 이름 요소, 탐욕이라는 뜻)',
  'hatticon': '핫디곤(하셀핫디곤의 이름 요소)',
  'havoth': '하봇(하봇야일의 이름 요소, 촌락들이라는 뜻)',
  'hazerim': '하세림(아위 사람들의 촌락 지역)',
  'hazezon': '하사손(하사손다말의 이름 요소)',
  'hazzurim': '핫수림(헬갓핫수림의 이름 요소, 칼날의 밭)',
  'hebrewess': '히브리 여자',
  'hepherites': '헤벨 가족, 헤벨 자손',
  'hezronites': '헤스론 가족, 헤스론 자손',
  'hizkiah': '히스기야(성경 인명)',
  'hizkijah': '히스기야(성경 인명)',
  'hodshi': '홋시(닷딤홋시의 이름 요소)',
  'hogla': '호글라(벧호글라의 이름 요소)',
  'hoglah': '호글라(슬로브핫의 딸)',
  'hophra': '바로 호브라(애굽 왕)',
  'horon': '호론(벧호론의 이름 요소)',
  'hozeh': '호세(골호세의 이름 요소)',
  'huz': '우스(성경 인명)',
  'huzoth': '후솟(기럇후솟의 이름 요소)',
  'huzzab': '훗삽, 나훔 2:7의 왕후 또는 높임받던 여인',
  'ije': '이예(이예아바림의 이름 요소)',
  'irpeel': '이르브엘(베냐민 지파의 성읍)',
  'iscah': '이스가(하란의 딸)',
  'ishbi': '이스비(이스비브놉의 이름 요소)',
  'ishmeelite': '이스마엘 사람',
  'ishmeelites': '이스마엘 사람들',
  'ishod': '이스훗(성경 인명)',
  'ispah': '이스바(성경 인명)',
  'ithmah': '이드마(모압 사람)',
  'ithrite': '이델 사람',
  'ithrites': '이델 사람들',
  'ittah': '엣(엣가신의 이름 요소)',
  'izeharites': '이스할 가족, 이스할 자손',
  'izharites': '이스할 자손들',
  'izrahite': '이스라 사람',
  'jaakan': '야아간(브네야아간의 이름 요소)',
  'jaan': '야안(다냐안의 이름 요소)',
  'jaazer': '야셀(길르앗의 성읍)',
  'jachinites': '야긴 가족, 야긴 자손',
  'jah': '야, 여호와를 가리키는 축약 이름',
  'jahaziah': '야스야(성경 인명)',
  'jahleel': '얄르엘(스불론의 아들)',
  'jahleelites': '얄르엘 가족, 얄르엘 자손',
  'jahzah': '야사(르우벤 지파의 성읍)',
  'jahzeel': '야스엘(납달리의 아들)',
  'jahzeelites': '야셀 가족, 야스엘 자손',
  'japhleti': '야블렛 사람',
  'japho': '욥바(지중해 연안의 성읍)',
  'jarkon': '얄곤(메얄곤의 이름 요소)',
  'jashubites': '야숩 가족, 야숩 자손',
  'jaziz': '야시스(다윗의 양 떼를 맡은 하갈 사람)',
  'jearim': '여아림(기럇여아림의 이름 요소)',
  'jeezerites': '이에셀 가족, 이에셀 자손',
  'jegar': '여갈(여갈사하두다의 이름 요소)',
  'jehizkiah': '여히스기야(에브라임의 지도자)',
  'jekabzeel': '여갑스엘(유다의 성읍)',
  'jephthae': '입다(이스라엘의 사사, 헬라식 표기)',
  'jerahmeelites': '여라므엘 사람들',
  'jeshimon': '여시몬, 사람이 살지 않는 황무지',
  'jeshimoth': '여시못(벧여시못의 이름 요소)',
  'jesiah': '잇시야(성경 인명)',
  'jesimoth': '여시못(벧여시못의 다른 철자)',
  'jesui': '이스위(아셀의 아들)',
  'jethlah': '이들라(단 지파의 성읍)',
  'jetur': '여둘(이스마엘의 아들)',
  'jeuz': '여우스(성경 인명)',
  'jezerites': '예셀 가족, 예셀 자손',
  'jeziah': '잇시야(성경 인명)',
  'jezoar': '이소할(성경 인명)',
  'jezreel': '이스르엘(성경 인명과 지명)',
  'jezreelitess': '이스르엘 여자',
  'jiphtah': '입다(유다 지파의 성읍)',
  'jiphthah': '입다(입다엘 골짜기의 이름 요소)',
  'jireh': '이레(여호와이레의 이름 요소, 준비하신다는 뜻)',
  'jod': '요드, 히브리 문자의 열째 글자',
  'jona': '요나(바요나의 이름 요소)',
  'josedech': '여호사닥(대제사장 여호수아의 아버지)',
  'jushab': '유삽(유삽헤셋의 이름 요소)',
  'kabzeel': '갑스엘(유다 남부의 성읍)',
  'karkaa': '갈가(유다 남쪽 경계의 지명)',
  'karkor': '갈골(미디안 지역의 지명)',
  'kartah': '가르다(스불론 지파의 레위 성읍)',
  'kazin': '가신(엣가신의 이름 요소)',
  'kenezite': '그나스 사람',
  'kenite': '겐 사람',
  'kenizzites': '그니스 족속 사람들',
  'keziz': '그시스(에멕그시스의 이름 요소)',
  'koph': '코프, 히브리 문자의 열아홉째 글자',
  'korahites': '고라 자손들',
  'korathites': '고라 가족',
  'korhites': '고라 사람들',
  'koz': '고스 또는 학고스(제사장 가문의 이름)',
  'labben': '랍벤(뭇랍벤의 시편 곡명 요소)',
  'lahai': '라해(브엘라해로이의 이름 요소, 살아 계셔서 보신다는 뜻)',
  'lasha': '라사(가나안 경계의 성읍)',
  'lebana': '르바나(성전 봉사자 가문의 이름)',
  'lebaoth': '르바옷(유다 남부의 성읍)',
  'lebbeus': '다대오, 르배오라고도 불린 예수의 제자',
  'lehem': '레헴(베들레헴의 이름 요소)',
  'lehemite': '베들레헴 사람',
  'libnath': '립낫(시홀립낫의 이름 요소)',
  'lubims': '루빔, 리비아계 사람들',
  'lud': '룻 또는 루드(셈의 아들, 민족 이름)',
  'lystra': '루스드라(소아시아의 도시)',
  'maachathite': '마아가 사람',
  'maaleh': '비탈, 아그랍빔 비탈의 이름 요소',
  'machirites': '마길 가족, 마길 자손',
  'maher': '마헬(마헬살랄하스바스의 이름 요소, 빠르다는 뜻)',
  'marcaboth': '말가봇(벧말가봇의 이름 요소)',
  'mazzaroth': '열두 궁성, 별자리들의 운행',
  'meah': '함메아 망대, 백이라는 뜻의 망대 이름',
  'meholah': '므홀라(아벨므홀라의 이름 요소)',
  'mehunims': '므우님 또는 마온 사람들',
  'melah': '멜라(델멜라의 이름 요소)',
  'melech': '멜렉(왕이라는 뜻의 이름 요소)',
  'melicu': '말루기(제사장 가문의 이름)',
  'meon': '므온(바알므온과 벧바알므온의 이름 요소)',
  'mercurius': '허메, 그리스 신 헤르메스의 라틴식 이름',
  'meron': '므론(성경 지명의 이름 요소)',
  'metheg': '메덱(메덱암마의 이름 요소)',
  'methoar': '므도알(림몬므도알의 이름 요소)',
  'miphkad': '밉갓(함밉갓 문의 이름 요소, 점호라는 뜻)',
  'mishpat': '미스밧(엔미스밧의 이름 요소, 심판이라는 뜻)',
  'mishraites': '미스라 족속',
  'missabib': '밋사빕(마골밋사빕의 이름 요소, 사방의 두려움이라는 뜻)',
  'mithnite': '미덴 사람',
  'mizpah': '미스바(파수대라는 뜻의 성경 지명)',
  'mizpeh': '미스베 또는 미스바(성경 지명)',
  'muth': '뭇(뭇랍벤의 시편 곡명 요소)',
  'naharaim': '나하라임(두 강 사이라는 뜻, 메소보다미아 지역)',
  'nechoh': '느고(애굽 왕 바로느고의 이름)',
  'neginah': '현악, 현악기에 맞춘 시편 곡명',
  'nego': '느고(아벳느고의 이름 요소)',
  'nehiloth': '관악, 관악기에 맞춘 시편 곡명',
  'netophathite': '느도바 사람',
  'netophathites': '느도바 사람들',
  'nibhaz': '닙하스(아와 사람들이 섬긴 우상)',
  'nimrah': '니므라(벧니므라의 이름 요소)',
  'nissi': '닛시(여호와닛시의 이름 요소, 나의 깃발이라는 뜻)',
  'ophrah': '오브라(성경 인명과 지명)',
  'oregim': '오르김(야레오르김의 이름 요소, 베 짜는 자들이라는 뜻)',
  'orpah': '오르바(룻의 동서)',
  'ozias': '웃시야(유다 왕의 헬라식 표기)',
  'oznites': '오스니 가족, 오스니 자손',
  'paaneah': '바네아(사브낫바네아의 이름 요소)',
  'pacatiana': '파카티아나(고대 브루기아 지역의 명칭)',
  'palet': '벨렛(벧벨렛의 이름 요소)',
  'palluites': '발루 가족, 발루 자손',
  'pannag': '판낙, 두로에 수출한 밀 또는 과자류',
  'parez': '베레스(림몬베레스의 이름 요소)',
  'pau': '바우(에돔 왕 하달의 도성)',
  'pazzez': '바세스(벧바세스의 이름 요소)',
  'pekod': '브곳(바벨론의 지역 또는 민족)',
  'pelatiah': '블라댜(성경 인명)',
  'pelonite': '블론 사람',
  'peor': '브올(모압의 산과 지명)',
  'perazim': '브라심(바알브라심의 이름 요소)',
  'perizzite': '브리스 사람',
  'perizzites': '브리스 족속 사람들',
  'phalec': '벨렉(성경 인명의 헬라식 표기)',
  'pharez': '베레스(유다의 아들)',
  'pharzites': '베레스 가족, 베레스 자손',
  'phelet': '벨렛(벧벨렛의 이름 요소)',
  'pherah': '베라(보디베라의 이름 요소)',
  'philistim': '블레셋 사람들',
  'pilneser': '빌레셀(디글랏빌레셀의 이름 요소)',
  'pispah': '비스바(성경 인명)',
  'pochereth': '보게렛(보게렛하스바임 가문의 이름 요소)',
  'porcius': '보르기오(총독 베스도의 로마식 가문 이름)',
  'poti': '보디(보디베라의 이름 요소)',
  'prochorus': '브로고로(초대 교회의 일곱 일꾼 중 한 사람)',
  'publius': '보블리오(멜리데 섬의 지도자)',
  'puhites': '붓 족속',
  'puteoli': '보디올(이탈리아의 항구 도시)',
  'rab': '랍, 앗수르의 고위 관직을 나타내는 칭호',
  'rabbim': '랍빔(바드랍빔의 이름 요소)',
  'ragau': '르우(예수의 족보에 나오는 인명)',
  'rapha': '르바(벧르바의 이름 요소)',
  'rechokim': '르호김(요낫엘렘르호김의 시편 곡명 요소)',
  'rishathaim': '리사다임(구산리사다임의 이름 요소)',
  'rizpah': '리스바(사울의 첩)',
  'rogel': '로겔(엔로겔의 이름 요소)',
  'ruhamah': '루하마(로루하마의 이름 요소, 긍휼히 여김이라는 뜻)',
  'sabachthani': '나를 버리셨나이까(엘리 엘리 라마 사박다니의 아람어)',
  'sahadutha': '사하두다(여갈사하두다의 이름 요소, 증거의 무더기라는 뜻)',
  'samech': '사메크, 히브리 문자의 열다섯째 글자',
  'sannah': '산나(기럇산나의 이름 요소)',
  'saph': '삽(블레셋의 거인)',
  'schin': '쉰, 히브리 문자의 스물한째 글자',
  'sepharvites': '스발와임 사람들',
  'sepher': '세벨(기럇세벨의 이름 요소, 책이라는 뜻)',
  'serah': '세라(성경 인명)',
  'seraphims': '스랍들, 하나님의 보좌 곁에 선 천사들',
  'shahar': '사할(세렛사할의 이름 요소)',
  'shalal': '살랄(마헬살랄하스바스의 이름 요소, 노략물이라는 뜻)',
  'shalisha': '살리사(에브라임 산지의 지역)',
  'sharezer': '사레셀(성경 인명)',
  'shean': '스안(벧스안의 이름 요소)',
  'shelanites': '셀라 가족, 셀라 자손',
  'shemesh': '세메스(벧세메스와 엔세메스의 이름 요소, 태양이라는 뜻)',
  'shemite': '벧세메스 사람',
  'sherah': '세에라(에브라임의 딸)',
  'shilonites': '실로 사람들',
  'shual': '수알(하살수알의 이름 요소)',
  'shuhite': '수아 사람',
  'shuphamites': '스부밤 가족, 스부밤 자손',
  'shuthalhites': '수델라 가족, 수델라 자손',
  'sinite': '신 족속 사람',
  'susim': '수심(하살수심의 이름 요소)',
  'syriack': '아람어, 시리아 말',
  'tachmonite': '다그몬 사람',
  'tahapanes': '다바네스 사람들 또는 다바네스의 자손',
  'tahpanhes': '다바네스(애굽의 성읍)',
  'tahtim': '닷딤(닷딤홋시의 이름 요소)',
  'tarpelites': '다블래 사람들',
  'taschith': '다스헷(알다스헷의 시편 곡명 요소, 멸하지 마소서라는 뜻)',
  'tekoah': '드고아(유다의 성읍)',
  'tekoite': '드고아 사람',
  'tekoites': '드고아 사람들',
  'tertullus': '더둘로(바울을 고소한 변사)',
  'thara': '데라(아브라함의 아버지, 헬라식 표기)',
  'tikvah': '디과(성경 인명)',
  'timeus': '디매오(바디매오의 아버지)',
  'tirshatha': '총독, 유다 지방의 페르시아식 행정 칭호',
  'tirzah': '디르사(성경 인명과 지명)',
  'tishbite': '디셉 사람',
  'tizite': '디스 사람',
  'tob': '돕(길르앗 동쪽의 지역)',
  'tolaites': '돌라 가족, 돌라 자손',
  'troas': '드로아(소아시아 북서부의 항구 도시)',
  'trogyllium': '드로길리움(소아시아 해안의 지명)',
  'trophimus': '드로비모(바울의 동역자)',
  'tzaddi': '차디, 히브리 문자의 열여덟째 글자',
  'uphaz': '우바스(금으로 유명한 성경의 지역)',
  'uz': '우스(성경 인명과 지명)',
  'uzzen': '우센(우센세에라의 이름 요소)',
  'uzziah': '웃시야(성경 인명과 유다 왕의 이름)',
  'vashni': '와스니, 역대상 6:28의 전승상 이름 또는 맏아들을 뜻하는 표현',
  'vau': '바브, 히브리 문자의 여섯째 글자',
  'zaccai': '삭개 가문',
  'zaccheus': '삭개오(여리고의 세리장)',
  'zacchur': '삭굴(성경 인명)',
  'zaccur': '삭굴(성경 인명)',
  'zacher': '세겔(성경 인명)',
  'zarah': '세라(유다의 아들, 헬라식 표기)',
  'zareathites': '소라 사람들',
  'zaza': '사사(성경 인명)',
  'zebaim': '스바임(보게렛하스바임 가문의 이름 요소)',
  'zebub': '세붑(바알세붑의 이름 요소, 파리라는 뜻)',
  'zebulunites': '스불론 지파 사람들',
  'zedek': '세덱(아도니세덱의 이름 요소, 의라는 뜻)',
  'zephathah': '스바다 골짜기',
  'zephon': '스본(바알스본의 이름 요소)',
  'zephonites': '스본 가족, 스본 자손',
  'zidkijah': '시드기야(성경 인명)',
  'zif': '시브월, 히브리력 둘째 달',
  'ziklag': '시글락(유다 남부의 성읍)',
  'zilthai': '실르대(성경 인명)',
  'ziphims': '십 사람들',
  'ziphites': '십 사람들',
  'ziz': '시스 고개',
  'zizah': '시사(성경 인명)',
  'zoheth': '소헷(성경 인명)',
  'zophai': '소배(성경 인명)',
  'zophim': '소빔 들(비스가 산 부근의 지역)',
  'zorathites': '소라 사람들',
  'zorites': '소라 사람들',
  'zuph': '숩(성경 인명과 지역)',
  'zur': '수르(미디안의 족장)',
  'zuzims': '수스 족속',
};
