// lib/core/database/seed_data/bible_books_seed.dart
// [NEW] 성경 66권 메타데이터 시드 데이터 (공개 도메인)
//
// 출처: 표준 성경 목록 (공개 도메인)
// testament: 'OT' (구약 39권) | 'NT' (신약 27권)

import 'package:drift/drift.dart';

import '../app_database.dart';

/// 66권 성경 목록을 Drift Companion 형태로 반환.
/// AppDatabase.onCreate 에서 삽입된다.
List<BibleBooksCompanion> bibleBooksSeed() => [
      // ══════════════════════════════════════════════════════
      // 구약 (Old Testament) — 39권
      // ══════════════════════════════════════════════════════

      _book(1, 'Genesis', '창세기', 'Gen', '창', 'OT', 1, 50),
      _book(2, 'Exodus', '출애굽기', 'Exod', '출', 'OT', 2, 40),
      _book(3, 'Leviticus', '레위기', 'Lev', '레', 'OT', 3, 27),
      _book(4, 'Numbers', '민수기', 'Num', '민', 'OT', 4, 36),
      _book(5, 'Deuteronomy', '신명기', 'Deut', '신', 'OT', 5, 34),
      _book(6, 'Joshua', '여호수아', 'Josh', '수', 'OT', 6, 24),
      _book(7, 'Judges', '사사기', 'Judg', '삿', 'OT', 7, 21),
      _book(8, 'Ruth', '룻기', 'Ruth', '룻', 'OT', 8, 4),
      _book(9, '1 Samuel', '사무엘상', '1Sam', '삼상', 'OT', 9, 31),
      _book(10, '2 Samuel', '사무엘하', '2Sam', '삼하', 'OT', 10, 24),
      _book(11, '1 Kings', '열왕기상', '1Kgs', '왕상', 'OT', 11, 22),
      _book(12, '2 Kings', '열왕기하', '2Kgs', '왕하', 'OT', 12, 25),
      _book(13, '1 Chronicles', '역대상', '1Chr', '대상', 'OT', 13, 29),
      _book(14, '2 Chronicles', '역대하', '2Chr', '대하', 'OT', 14, 36),
      _book(15, 'Ezra', '에스라', 'Ezra', '스', 'OT', 15, 10),
      _book(16, 'Nehemiah', '느헤미야', 'Neh', '느', 'OT', 16, 13),
      _book(17, 'Esther', '에스더', 'Esth', '에', 'OT', 17, 10),
      _book(18, 'Job', '욥기', 'Job', '욥', 'OT', 18, 42),
      _book(19, 'Psalms', '시편', 'Ps', '시', 'OT', 19, 150),
      _book(20, 'Proverbs', '잠언', 'Prov', '잠', 'OT', 20, 31),
      _book(21, 'Ecclesiastes', '전도서', 'Eccl', '전', 'OT', 21, 12),
      _book(22, 'Song of Solomon', '아가', 'Song', '아', 'OT', 22, 8),
      _book(23, 'Isaiah', '이사야', 'Isa', '사', 'OT', 23, 66),
      _book(24, 'Jeremiah', '예레미야', 'Jer', '렘', 'OT', 24, 52),
      _book(25, 'Lamentations', '예레미야애가', 'Lam', '애', 'OT', 25, 5),
      _book(26, 'Ezekiel', '에스겔', 'Ezek', '겔', 'OT', 26, 48),
      _book(27, 'Daniel', '다니엘', 'Dan', '단', 'OT', 27, 12),
      _book(28, 'Hosea', '호세아', 'Hos', '호', 'OT', 28, 14),
      _book(29, 'Joel', '요엘', 'Joel', '욜', 'OT', 29, 3),
      _book(30, 'Amos', '아모스', 'Amos', '암', 'OT', 30, 9),
      _book(31, 'Obadiah', '오바댜', 'Obad', '옵', 'OT', 31, 1),
      _book(32, 'Jonah', '요나', 'Jonah', '욘', 'OT', 32, 4),
      _book(33, 'Micah', '미가', 'Mic', '미', 'OT', 33, 7),
      _book(34, 'Nahum', '나훔', 'Nah', '나', 'OT', 34, 3),
      _book(35, 'Habakkuk', '하박국', 'Hab', '합', 'OT', 35, 3),
      _book(36, 'Zephaniah', '스바냐', 'Zeph', '습', 'OT', 36, 3),
      _book(37, 'Haggai', '학개', 'Hag', '학', 'OT', 37, 2),
      _book(38, 'Zechariah', '스가랴', 'Zech', '슥', 'OT', 38, 14),
      _book(39, 'Malachi', '말라기', 'Mal', '말', 'OT', 39, 4),

      // ══════════════════════════════════════════════════════
      // 신약 (New Testament) — 27권
      // ══════════════════════════════════════════════════════

      _book(40, 'Matthew', '마태복음', 'Matt', '마', 'NT', 40, 28),
      _book(41, 'Mark', '마가복음', 'Mark', '막', 'NT', 41, 16),
      _book(42, 'Luke', '누가복음', 'Luke', '눅', 'NT', 42, 24),
      _book(43, 'John', '요한복음', 'John', '요', 'NT', 43, 21),
      _book(44, 'Acts', '사도행전', 'Acts', '행', 'NT', 44, 28),
      _book(45, 'Romans', '로마서', 'Rom', '롬', 'NT', 45, 16),
      _book(46, '1 Corinthians', '고린도전서', '1Cor', '고전', 'NT', 46, 16),
      _book(47, '2 Corinthians', '고린도후서', '2Cor', '고후', 'NT', 47, 13),
      _book(48, 'Galatians', '갈라디아서', 'Gal', '갈', 'NT', 48, 6),
      _book(49, 'Ephesians', '에베소서', 'Eph', '엡', 'NT', 49, 6),
      _book(50, 'Philippians', '빌립보서', 'Phil', '빌', 'NT', 50, 4),
      _book(51, 'Colossians', '골로새서', 'Col', '골', 'NT', 51, 4),
      _book(52, '1 Thessalonians', '데살로니가전서', '1Thess', '살전', 'NT', 52, 5),
      _book(53, '2 Thessalonians', '데살로니가후서', '2Thess', '살후', 'NT', 53, 3),
      _book(54, '1 Timothy', '디모데전서', '1Tim', '딤전', 'NT', 54, 6),
      _book(55, '2 Timothy', '디모데후서', '2Tim', '딤후', 'NT', 55, 4),
      _book(56, 'Titus', '디도서', 'Titus', '딛', 'NT', 56, 3),
      _book(57, 'Philemon', '빌레몬서', 'Phlm', '몬', 'NT', 57, 1),
      _book(58, 'Hebrews', '히브리서', 'Heb', '히', 'NT', 58, 13),
      _book(59, 'James', '야고보서', 'Jas', '약', 'NT', 59, 5),
      _book(60, '1 Peter', '베드로전서', '1Pet', '벧전', 'NT', 60, 5),
      _book(61, '2 Peter', '베드로후서', '2Pet', '벧후', 'NT', 61, 3),
      _book(62, '1 John', '요한일서', '1John', '요일', 'NT', 62, 5),
      _book(63, '2 John', '요한이서', '2John', '요이', 'NT', 63, 1),
      _book(64, '3 John', '요한삼서', '3John', '요삼', 'NT', 64, 1),
      _book(65, 'Jude', '유다서', 'Jude', '유', 'NT', 65, 1),
      _book(66, 'Revelation', '요한계시록', 'Rev', '계', 'NT', 66, 22),
    ];

BibleBooksCompanion _book(
  int id,
  String name,
  String nameKorean,
  String abbr,
  String abbrKorean,
  String testament,
  int order,
  int chapters,
) =>
    BibleBooksCompanion(
      id: Value(id),
      name: Value(name),
      nameKorean: Value(nameKorean),
      abbreviation: Value(abbr),
      abbreviationKorean: Value(abbrKorean),
      testament: Value(testament),
      orderIndex: Value(order),
      chapterCount: Value(chapters),
    );

/// 책 ID → 이름 빠른 조회 맵 (앱 전체에서 재사용).
const Map<int, ({String en, String ko, String abbr, String abbrKo})>
    bookNameMap = {
  1: (en: 'Genesis', ko: '창세기', abbr: 'Gen', abbrKo: '창'),
  2: (en: 'Exodus', ko: '출애굽기', abbr: 'Exod', abbrKo: '출'),
  3: (en: 'Leviticus', ko: '레위기', abbr: 'Lev', abbrKo: '레'),
  4: (en: 'Numbers', ko: '민수기', abbr: 'Num', abbrKo: '민'),
  5: (en: 'Deuteronomy', ko: '신명기', abbr: 'Deut', abbrKo: '신'),
  6: (en: 'Joshua', ko: '여호수아', abbr: 'Josh', abbrKo: '수'),
  7: (en: 'Judges', ko: '사사기', abbr: 'Judg', abbrKo: '삿'),
  8: (en: 'Ruth', ko: '룻기', abbr: 'Ruth', abbrKo: '룻'),
  9: (en: '1 Samuel', ko: '사무엘상', abbr: '1Sam', abbrKo: '삼상'),
  10: (en: '2 Samuel', ko: '사무엘하', abbr: '2Sam', abbrKo: '삼하'),
  11: (en: '1 Kings', ko: '열왕기상', abbr: '1Kgs', abbrKo: '왕상'),
  12: (en: '2 Kings', ko: '열왕기하', abbr: '2Kgs', abbrKo: '왕하'),
  13: (en: '1 Chronicles', ko: '역대상', abbr: '1Chr', abbrKo: '대상'),
  14: (en: '2 Chronicles', ko: '역대하', abbr: '2Chr', abbrKo: '대하'),
  15: (en: 'Ezra', ko: '에스라', abbr: 'Ezra', abbrKo: '스'),
  16: (en: 'Nehemiah', ko: '느헤미야', abbr: 'Neh', abbrKo: '느'),
  17: (en: 'Esther', ko: '에스더', abbr: 'Esth', abbrKo: '에'),
  18: (en: 'Job', ko: '욥기', abbr: 'Job', abbrKo: '욥'),
  19: (en: 'Psalms', ko: '시편', abbr: 'Ps', abbrKo: '시'),
  20: (en: 'Proverbs', ko: '잠언', abbr: 'Prov', abbrKo: '잠'),
  21: (en: 'Ecclesiastes', ko: '전도서', abbr: 'Eccl', abbrKo: '전'),
  22: (en: 'Song of Solomon', ko: '아가', abbr: 'Song', abbrKo: '아'),
  23: (en: 'Isaiah', ko: '이사야', abbr: 'Isa', abbrKo: '사'),
  24: (en: 'Jeremiah', ko: '예레미야', abbr: 'Jer', abbrKo: '렘'),
  25: (en: 'Lamentations', ko: '예레미야애가', abbr: 'Lam', abbrKo: '애'),
  26: (en: 'Ezekiel', ko: '에스겔', abbr: 'Ezek', abbrKo: '겔'),
  27: (en: 'Daniel', ko: '다니엘', abbr: 'Dan', abbrKo: '단'),
  28: (en: 'Hosea', ko: '호세아', abbr: 'Hos', abbrKo: '호'),
  29: (en: 'Joel', ko: '요엘', abbr: 'Joel', abbrKo: '욜'),
  30: (en: 'Amos', ko: '아모스', abbr: 'Amos', abbrKo: '암'),
  31: (en: 'Obadiah', ko: '오바댜', abbr: 'Obad', abbrKo: '옵'),
  32: (en: 'Jonah', ko: '요나', abbr: 'Jonah', abbrKo: '욘'),
  33: (en: 'Micah', ko: '미가', abbr: 'Mic', abbrKo: '미'),
  34: (en: 'Nahum', ko: '나훔', abbr: 'Nah', abbrKo: '나'),
  35: (en: 'Habakkuk', ko: '하박국', abbr: 'Hab', abbrKo: '합'),
  36: (en: 'Zephaniah', ko: '스바냐', abbr: 'Zeph', abbrKo: '습'),
  37: (en: 'Haggai', ko: '학개', abbr: 'Hag', abbrKo: '학'),
  38: (en: 'Zechariah', ko: '스가랴', abbr: 'Zech', abbrKo: '슥'),
  39: (en: 'Malachi', ko: '말라기', abbr: 'Mal', abbrKo: '말'),
  40: (en: 'Matthew', ko: '마태복음', abbr: 'Matt', abbrKo: '마'),
  41: (en: 'Mark', ko: '마가복음', abbr: 'Mark', abbrKo: '막'),
  42: (en: 'Luke', ko: '누가복음', abbr: 'Luke', abbrKo: '눅'),
  43: (en: 'John', ko: '요한복음', abbr: 'John', abbrKo: '요'),
  44: (en: 'Acts', ko: '사도행전', abbr: 'Acts', abbrKo: '행'),
  45: (en: 'Romans', ko: '로마서', abbr: 'Rom', abbrKo: '롬'),
  46: (en: '1 Corinthians', ko: '고린도전서', abbr: '1Cor', abbrKo: '고전'),
  47: (en: '2 Corinthians', ko: '고린도후서', abbr: '2Cor', abbrKo: '고후'),
  48: (en: 'Galatians', ko: '갈라디아서', abbr: 'Gal', abbrKo: '갈'),
  49: (en: 'Ephesians', ko: '에베소서', abbr: 'Eph', abbrKo: '엡'),
  50: (en: 'Philippians', ko: '빌립보서', abbr: 'Phil', abbrKo: '빌'),
  51: (en: 'Colossians', ko: '골로새서', abbr: 'Col', abbrKo: '골'),
  52: (en: '1 Thessalonians', ko: '데살로니가전서', abbr: '1Thess', abbrKo: '살전'),
  53: (en: '2 Thessalonians', ko: '데살로니가후서', abbr: '2Thess', abbrKo: '살후'),
  54: (en: '1 Timothy', ko: '디모데전서', abbr: '1Tim', abbrKo: '딤전'),
  55: (en: '2 Timothy', ko: '디모데후서', abbr: '2Tim', abbrKo: '딤후'),
  56: (en: 'Titus', ko: '디도서', abbr: 'Titus', abbrKo: '딛'),
  57: (en: 'Philemon', ko: '빌레몬서', abbr: 'Phlm', abbrKo: '몬'),
  58: (en: 'Hebrews', ko: '히브리서', abbr: 'Heb', abbrKo: '히'),
  59: (en: 'James', ko: '야고보서', abbr: 'Jas', abbrKo: '약'),
  60: (en: '1 Peter', ko: '베드로전서', abbr: '1Pet', abbrKo: '벧전'),
  61: (en: '2 Peter', ko: '베드로후서', abbr: '2Pet', abbrKo: '벧후'),
  62: (en: '1 John', ko: '요한일서', abbr: '1John', abbrKo: '요일'),
  63: (en: '2 John', ko: '요한이서', abbr: '2John', abbrKo: '요이'),
  64: (en: '3 John', ko: '요한삼서', abbr: '3John', abbrKo: '요삼'),
  65: (en: 'Jude', ko: '유다서', abbr: 'Jude', abbrKo: '유'),
  66: (en: 'Revelation', ko: '요한계시록', abbr: 'Rev', abbrKo: '계'),
};
